export default {
  login: 'PadillaTom',
  id: 59969816,
  node_id: 'MDQ6VXNlcjU5OTY5ODE2',
  avatar_url: 'https://avatars0.githubusercontent.com/u/59969816?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/PadillaTom',
  html_url: 'https://github.com/PadillaTom',
  followers_url: 'https://api.github.com/users/PadillaTom/followers',
  following_url:
    'https://api.github.com/users/PadillaTom/following{/other_user}',
  gists_url: 'https://api.github.com/users/PadillaTom/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/PadillaTom/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/PadillaTom/subscriptions',
  organizations_url: 'https://api.github.com/users/PadillaTom/orgs',
  repos_url: 'https://api.github.com/users/PadillaTom/repos',
  events_url: 'https://api.github.com/users/PadillaTom/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/PadillaTom/received_events',
  type: 'User',
  site_admin: false,
  name: 'Tom',
  company: null,
  blog: 'https://www.linkedin.com/in/padillatom/',
  location: 'Geneva',
  email: null,
  hireable: null,
  bio: 'Front-End Web Developer || Self-Taught ',
  twitter_username: null,
  public_repos: 19,
  public_gists: 0,
  followers: 0,
  following: 5,
  created_at: '2020-01-16T15:54:32Z',
  updated_at: '2020-09-03T13:09:58Z',
};
